---
title: "Arnéodo-Coullet-Tresser System"
---

## System description

The governing equations of this chaotic system are

$$
\begin{eqnarray}
\dot{x} &=& ax-y\\
\dot{y} &=& -y+xz+x^3\\
\dot{z} &=& -bz+xy-z^2
\end{eqnarray}
$$

with $a=0.58,b=0.2$ and initial condition $(-2,-1,0)$.

An animation of the pre-computed solution trajectory for the given chaotic
system is presented below. The trajectory, spanning 10^3^ seconds, is colored
according to the calculated local [Lyapunov exponents](https://en.wikipedia.org/wiki/Lyapunov_exponent){target="blank"} at each point in time.

<video width="90%" style="display: block; margin: 0 auto;" controls muted autoplay loop>
  <source src="https://github.com/Ramkumar47/ComputationalCodes/blob/main/29_VisualizingChaoticSystems/35_Arneodo-Coullet-Tresser_System/animation.mp4?raw=true" type="video/webm">
</video>
A left-to-right 360^o^ view of the chaotic system trajectory

The colormap selected for the aforementioned animation employs a blue-green-red gradient. The blue to green range corresponds to negative Lyapunov exponents, signifying regions where the system's predictability decreases. Conversely, the green to red range corresponds to positive Lyapunov exponents, indicative of regions where the system exhibits an increase in unpredictability.
 
## Real-time simulation 

The real-time simulation can be executed up to the designated end
time as indicated below. As the simulation progresses, the 3D view of trajectory
evolution can be explored by click-drag & scroll options in the mouse/touchpad.

The visualization was made using     [P5.js](https://p5js.org/){target="blank"}.
 
```{=html}
<iframe width="800" height="800"
src="https://editor.p5js.org/RamkumarRK47/full/SLExYLbwD"></iframe>
```
